# Generated by Django 6.0.2 on 2026-02-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=255, unique=True)),
                ('priority', models.CharField(max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
