# Generated by Django 5.2.11 on 2026-02-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_read_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_id',
            field=models.CharField(db_index=True, default='', max_length=128),
        ),
    ]
