# Generated by Django 5.2.11 on 2026-02-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='response_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
