# Generated by Django 6.0.2 on 2026-02-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_user_id_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Unassigned', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority_justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_id',
            field=models.CharField(help_text='ID del usuario que creó el ticket (referencia lógica, no FK)', max_length=255),
        ),
    ]
