# Generated by Django 6.0.2 on 2026-02-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_user_id_ticketresponse'),
        ('tickets', '0003_ticket_priority_ticket_priority_justification_and_more'),
    ]

    operations = [
    ]
